baseURL = 'https://clairekiu.github.io/'
languageCode = 'kr-ko'
title = '@nimeajku'
theme = 'hugo-PaperMod'
relativeURLs = true
preserveTaxonomyNames = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params.widgets]
  [[params.widgets.sidebar]]
    name = "tags"
    title = "Tags"
    weight = 1

[params.tagOptions]
  showCount = true


[params]
  ShowCodeCopyButtons = true
  comments = true
  ShowBreadCrumbs = true
  disableSpecial1stPost = true


  [params.homeInfoParams]
    Title = "clairekiu.github.io"
    Content = "ğŸ€ ë‚´ ë¨¸ë¦¿ì† ë¬¸ì„œí™” í˜ì´ì§€ ..."